after_training: null
agent: deeprl.tensorflow.agents.A2C(layers=(64, 64))
before_training: null
checkpoint: last
environment: deeprl.environments.Bullet('AntBulletEnv-v5')
environment_name: null
header: import deeprl.tensorflow
name: null
parallel: 1
path: null
seed: 0
sequential: 1
test_environment: null
trainer: null
